// extracting the task order fields
export const taskOrderFields = [
	'adc',
	'wbs_task_code',
	'business_unit_manager',
	'category',
	'customID',
	'departure',
	'destination',
	'email',
	'expenses',
	'first_note',
	'framework',
	'last_note',
	'legal_entity',
	'mt_cost',
	'name',
	'office',
	'project_title',
	'revision_no',
	'status',
	'task_order_category',
	'areExpensesIncluded',
	'areRatesVerified',
	'areTheWbsCodesConfirmed',
	'gmAuthorizationMustBeAttached',
	'haveTheMultipliersBeenVerified',
	'isApproved',
	'isItAtoWithAjacobsOffice',
	'isTheOfficeLocationVerified',
	'isThePersonBillable',
	'startDate',
	'endDate',
	'Created',
	'Modified',
];

// extracting the resource table list fields
export const resourceTableFields = [
	'bare_cost',
	'bwr',
	'first_name',
	'framework',
	'function',
	'jesa_billable',
	'last_name',
	'requestId',
	'total_labor_cost',
	'total_labor_hours',
	'wbs',
	'm_total',
	'_x006d_1',
	'_x006d_2',
	'_x006d_3',
	'_x006d_4',
	'_x006d_5',
	'_x006d_6',
	'_x006d_7',
	'_x006d_8',
	'_x006d_9',
	'_x006d_10',
	'_x006d_11',
	'_x006d_12',
];

export const timelineFields = [
	'createdAt',
	'description',
	'requestId',
	'framework',
	'icon',
	'color',
];

export const attachmentsFields = [
	'file_title',
	'version',
	'comment',
	'whenCreated',
	'documentURL',
	'who_created',
	'requestId',
	'framework',
];
