// This file contains some dummy mock data. This is only for testing purposes.
export const dataflow = [
	{
		adc: 23242.4234,
		wbsTaskCode: 'formData.wbsTaskCode',
		businessUnitManager: 'formData.businessUnitManager',
		category: 'formData.category',
		customID: 'formData.customID',
		departure: 'formData.departure',
		destination: 'formData.destination',
		email: 'formData.email',
		expenses: 'formData.expenses',
		firstNote: 'formData.firstNote',
		framework: 'psa',
		lastNote: 'formData.lastNote',
		legalEntity: 'formData.legalEntity',
		mtCost: 34534,
		name: 'formData.name',
		office: 'formData.office',
		projectTitle: 'formData.projectTitle',
		revisionNo: 342.342342,
		status: 'active',
		taskOrderCategory: 'formData.taskOrderCategory',
		areExpensesIncluded: 'Yes',
		areRatesVerified: 'No',
		areTheWbsCodesConfirmed: 'No',
		gmAuthorizationMustBeAttached: 'Yes',
		haveTheMultipliersBeenVerified: 'Yes',
		isApproved: 'No',
		isItAtoWithAjacobsOffice: 'No',
		isTheOfficeLocationVerified: 'Yes',
		isThePersonBillable: 'No',
		startDate: 'formData.startDate',
		endDate: 'formData.endDate',
	},
	{
		adc: 23242.4234,
		wbsTaskCode: '.wbsTaskCode',
		businessUnitManager: '.businessUnitManager',
		category: '.category',
		customID: '.customID',
		departure: '.departure',
		destination: '.destination',
		email: '.email',
		expenses: '.expenses',
		firstNote: '.firstNote',
		framework: 'psa',
		lastNote: '.lastNote',
		legalEntity: '.legalEntity',
		mtCost: 5534,
		name: '.name',
		office: '.office',
		projectTitle: '.projectTitle',
		revisionNo: 342.342342,
		status: 'active',
		taskOrderCategory: '.taskOrderCategory',
		areExpensesIncluded: 'Yes',
		areRatesVerified: 'No',
		areTheWbsCodesConfirmed: 'No',
		gmAuthorizationMustBeAttached: 'Yes',
		haveTheMultipliersBeenVerified: 'Yes',
		isApproved: 'No',
		isItAtoWithAjacobsOffice: 'No',
		isTheOfficeLocationVerified: 'Yes',
		isThePersonBillable: 'No',
		startDate: 'formData.startDate',
		endDate: 'formData.endDate',
	},
];

export const resourcedata = [
	{
		bareCost: 'resource.bareCost',
		bwr: 'resource.bwr',
		firstName: 'resource.firstName',
		framework: 'psa',
		functionn: 'resource.function',
		jesaBillable: 'resource.jesaBillable',
		lastName: 'resource.lastName',
		_x006d_1: 3,
		_x006d_2: 34,
		_x006d_3: 34,
		_x006d_4: 2,
		_x006d_5: 35,
		_x006d_6: 343,
		_x006d_7: 450,
		_x006d_8: 30,
		_x006d_9: 3,
		_x006d_10: 32,
		_x006d_11: 333,
		_x006d_12: 2,
		mTotal: 2340,
		requestId: '.customID',
		totalLaborCost: 23,
		totalLaborHours: 3,
		wbs: 'AAA.Kas.sf',
	},
	{
		bareCost: '.bareCost',
		bwr: '.bwr',
		firstName: '.firstName',
		framework: 'psa',
		functionn: '.function',
		jesaBillable: '.jesaBillable',
		lastName: '.lastName',
		_x006d_1: 2,
		_x006d_2: 24,
		_x006d_3: 24,
		_x006d_4: 2,
		_x006d_5: 25,
		_x006d_6: 243,
		_x006d_7: 250,
		_x006d_8: 30,
		_x006d_9: 3,
		_x006d_10: 32,
		_x006d_11: 333,
		_x006d_12: 2,
		mTotal: 22320,
		requestId: 'formData.customID',
		totalLaborCost: 23,
		totalLaborHours: 3,
		wbs: 'BBB.Kas.sf',
	},
];

export const attachments = [
	{
		version: 'v10',
		whenCreated: 'sfssa',
		whoCreated: 'Clifford',
		comment: 'Hello',
		fileTitle: 'Hours split',
		documentURL: 'asf',
		requestId: 'formData.customID',
		framework: 'psa',
	},
	{
		version: 'v10',
		whenCreated: 'sfssa',
		whoCreated: 'Clifford',
		comment: 'Hello',
		fileTitle: 'asfs',
		documentURL: 'asf',
		requestId: '.customID',
		framework: 'psa',
	},
];

export const timelines = [
	{
		createdAt: new Date().toDateString(),
		description: 'Rejected Request',
		requestId: 'customID',
		framework: 'psa',
		color: 'danger-color',
		icon: 'times',
	},
	{
		createdAt: new Date().toDateString(),
		description: 'Approved Request',
		requestId: 'formData.customID',
		framework: 'psa',
		color: 'success-color',
		icon: 'check',
	},
];
